/**
 * Provides shared files behavior for CLI execution.
 */
import {
  cpSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, relative } from "node:path";

import { hashText } from "@_molaidrislabs/shared";

import type { RnMtCliOwnershipMetadataFile } from "../types";

/**
 * Encapsulates files behavior behind a constructor-backed seam.
 */
export class RnMtCliFilesModule {
  /**
   * Initializes the files with its shared dependencies.
   */
  constructor(
    private readonly dependencies: {
      fileExists: (path: string) => boolean;
      readFile: (path: string) => string;
      writeFile: (path: string, contents: string) => void;
    },
  ) {}

  /**
   * Ensures the parent directory exists before the CLI writes a generated file.
   */
  ensureParentDir(path: string) {
    mkdirSync(dirname(path), { recursive: true });
  }

  /**
   * Reads file contents using raw bytes when needed for binary-safe compare and
   * write operations.
   */
  readPathContents(path: string, options: { binary?: boolean } = {}) {
    return options.binary
      ? readFileSync(path)
      : this.dependencies.readFile(path);
  }

  /**
   * Writes file contents using raw bytes when needed for binary-safe convert
   * and generated-file operations.
   */
  writePathContents(path: string, contents: string | Buffer) {
    if (Buffer.isBuffer(contents)) {
      writeFileSync(path, contents);
      return;
    }

    this.dependencies.writeFile(path, contents);
  }

  /**
   * Returns true when two file content payloads are byte-for-byte identical.
   */
  private contentsEqual(left: string | Buffer | null, right: string | Buffer) {
    if (left === null) {
      return false;
    }

    if (Buffer.isBuffer(left) && Buffer.isBuffer(right)) {
      return left.equals(right);
    }

    return left === right;
  }

  /**
   * Parses CLI ownership metadata and verifies that it has the expected shape.
   */
  private readOwnershipMetadata(path: string) {
    try {
      const parsed = JSON.parse(
        this.dependencies.readFile(path),
      ) as RnMtCliOwnershipMetadataFile;

      if (
        parsed.tool !== "rn-mt" ||
        parsed.owner !== "cli" ||
        !Array.isArray(parsed.artifacts)
      ) {
        throw new Error("Ownership metadata is not CLI-owned.");
      }

      return parsed;
    } catch {
      throw new Error(
        `Generated artifact ownership metadata is invalid: ${path}. Restore the CLI-owned metadata file or remove conflicting generated artifacts before rerunning the command.`,
      );
    }
  }

  /**
   * Returns true for generated current facade files from older sync/convert
   * runs whose ownership hash may be stale but whose contents are still clearly
   * CLI-owned.
   */
  private isGeneratedCurrentFacadeContents(contents: string | Buffer) {
    const text = Buffer.isBuffer(contents)
      ? contents.toString("utf8")
      : contents;

    return (
      text.startsWith(
        "// Generated by rn-mt. CLI-owned current facade. Do not edit directly.\n",
      ) ||
      text.startsWith(
        "// Generated by rn-mt. CLI-owned current runtime facade. Do not edit directly.\n",
      )
    );
  }

  /**
   * Returns an existing convert-owned artifact record that can be migrated into
   * sync ownership safely.
   */
  private getConvertOwnedArtifact(options: {
    ownershipRootDir: string;
    relativePath: string;
    kind: string;
    currentContents: string | Buffer | null;
  }) {
    const convertOwnershipMetadataPath = join(
      options.ownershipRootDir,
      "rn-mt.generated.convert.ownership.json",
    );

    if (!this.isReadableFile(convertOwnershipMetadataPath)) {
      return null;
    }

    const metadata = this.readOwnershipMetadata(convertOwnershipMetadataPath);
    const artifact = metadata.artifacts.find(
      (candidate) =>
        candidate.path === options.relativePath &&
        candidate.kind === options.kind,
    );

    if (!artifact || !options.currentContents) {
      return null;
    }

    if (
      artifact.hash &&
      artifact.hash !== hashText(options.currentContents) &&
      !(
        options.kind === "current-facade" &&
        this.isGeneratedCurrentFacadeContents(options.currentContents)
      )
    ) {
      throw new Error(
        `Generated artifact drift detected for ${join(
          options.ownershipRootDir,
          options.relativePath,
        )}. The file was modified outside rn-mt. Restore the CLI-owned file or remove it before rerunning the command.`,
      );
    }

    return artifact;
  }

  /**
   * Returns the default sibling output directory used for tenant handoff
   * exports.
   */
  getDefaultHandoffOutputDir(rootDir: string, tenantId: string) {
    return join(dirname(rootDir), `${basename(rootDir)}-handoff-${tenantId}`);
  }

  /**
   * Returns the default zip archive path for a handoff export directory.
   */
  getDefaultHandoffArchivePath(outputDir: string) {
    return `${outputDir}.zip`;
  }

  /**
   * Copies repo for handoff for the files flow.
   */
  copyRepoForHandoff(sourceDir: string, outputDir: string) {
    const skippedTopLevelNames = new Set([".git", "node_modules"]);

    cpSync(sourceDir, outputDir, {
      recursive: true,
      filter(sourcePath) {
        return !skippedTopLevelNames.has(basename(sourcePath));
      },
    });
  }

  /**
   * Returns true when a path exists and can be treated as a readable file.
   */
  isReadableFile(path: string) {
    if (!this.dependencies.fileExists(path)) {
      return false;
    }

    try {
      return statSync(path).isFile();
    } catch {
      return true;
    }
  }

  /**
   * Writes generated files for the files flow.
   */
  writeGeneratedFiles(
    generatedFilesToWrite: Array<{
      path: string;
      contents: string | Buffer;
      kind: string;
    }>,
    options: {
      ownershipMetadataPath?: string;
      allowedUntrackedOverwritePaths?: Set<string>;
    } = {},
  ) {
    const ownershipMetadataPath =
      options.ownershipMetadataPath ??
      generatedFilesToWrite.find((file) => file.kind === "ownership-metadata")
        ?.path ??
      null;
    const ownershipRootDir = ownershipMetadataPath
      ? dirname(ownershipMetadataPath)
      : null;
    let ownershipMetadata: RnMtCliOwnershipMetadataFile | null = null;

    if (ownershipMetadataPath && this.isReadableFile(ownershipMetadataPath)) {
      ownershipMetadata = this.readOwnershipMetadata(ownershipMetadataPath);
    }

    const ownershipByRelativePath = new Map(
      ownershipMetadata?.artifacts.map((artifact) => [
        artifact.path,
        artifact,
      ]) ?? [],
    );

    return generatedFilesToWrite.map((file) => {
      const fileExists = this.isReadableFile(file.path);
      const expectsBinary = Buffer.isBuffer(file.contents);
      const currentContents = fileExists
        ? this.readPathContents(file.path, { binary: expectsBinary })
        : null;
      const changed =
        !fileExists || !this.contentsEqual(currentContents, file.contents);

      if (changed && fileExists && ownershipMetadataPath && ownershipRootDir) {
        if (file.path === ownershipMetadataPath) {
          if (!ownershipMetadata) {
            throw new Error(
              `Refusing to overwrite ${file.path} because no CLI ownership metadata is available. Remove the conflicting file or restore the generated ownership metadata first.`,
            );
          }
        } else {
          const relativePath = relative(ownershipRootDir, file.path);
          const trackedArtifact = ownershipByRelativePath.get(relativePath);
          const convertOwnedArtifact =
            trackedArtifact || !currentContents
              ? null
              : this.getConvertOwnedArtifact({
                  ownershipRootDir,
                  relativePath,
                  kind: file.kind,
                  currentContents,
                });

          if (options.allowedUntrackedOverwritePaths?.has(file.path)) {
            // Convert intentionally replaces original root entry files with CLI-owned wrappers.
          } else {
            if (!ownershipMetadata && !convertOwnedArtifact) {
              throw new Error(
                `Refusing to overwrite generated artifact without CLI ownership metadata: ${file.path}. Remove the conflicting file or restore ${ownershipMetadataPath} before rerunning the command.`,
              );
            }

            if (trackedArtifact && trackedArtifact.kind !== file.kind) {
              throw new Error(
                `Generated artifact ownership conflict for ${file.path}. The file exists but is not tracked as CLI-owned in ${ownershipMetadataPath}.`,
              );
            }

            if (!trackedArtifact && !convertOwnedArtifact) {
              throw new Error(
                `Generated artifact ownership conflict for ${file.path}. The file exists but is not tracked as CLI-owned in ${ownershipMetadataPath}.`,
              );
            }

            const ownershipArtifact = trackedArtifact ?? convertOwnedArtifact;

            if (
              ownershipArtifact?.hash &&
              currentContents &&
              ownershipArtifact.hash !== hashText(currentContents) &&
              !(
                file.kind === "current-facade" &&
                this.isGeneratedCurrentFacadeContents(currentContents)
              )
            ) {
              throw new Error(
                `Generated artifact drift detected for ${file.path}. The file was modified outside rn-mt. Restore the CLI-owned file or remove it before rerunning the command.`,
              );
            }
          }
        }
      }

      if (changed) {
        this.ensureParentDir(file.path);
        this.writePathContents(file.path, file.contents);
      }

      return {
        path: file.path,
        kind: file.kind,
        changed,
        hash: hashText(file.contents),
      };
    });
  }
}
