/**
 * Builds generated native artifacts during sync.
 */
import { readdirSync } from "node:fs";
import { basename, join } from "node:path";

import type {
  RnMtManifest,
  RnMtResolvedRuntimeArtifact,
  RnMtResolvedTarget,
} from "../manifest/types";
import {
  getResolvedAndroidApplicationId,
  getResolvedIosBundleIdentifier,
} from "../manifest";
import { RnMtWorkspace } from "../workspace";

import type {
  RnMtExpoTargetContextArtifact,
  RnMtSyncGeneratedFile,
} from "./types";

/**
 * Returns true when the repo has an Expo config surface that should receive an
 * rn-mt target bridge.
 */
export function hasExpoComputedConfig(workspace: RnMtWorkspace) {
  return [
    join(workspace.rootDir, "app.config.ts"),
    join(workspace.rootDir, "app.config.js"),
    join(workspace.rootDir, "app.json"),
  ].some((path) => workspace.exists(path));
}

/**
 * Creates the generated Expo target-context bridge consumed by app.config.
 */
export function createExpoTargetContextFile(
  workspace: RnMtWorkspace,
  runtime: RnMtResolvedRuntimeArtifact,
  target: RnMtResolvedTarget,
  iconPath: string | undefined,
): RnMtSyncGeneratedFile {
  const expoConfig =
    runtime.config.expo &&
    typeof runtime.config.expo === "object" &&
    !Array.isArray(runtime.config.expo)
      ? (runtime.config.expo as {
          slug?: string;
          scheme?: string | string[];
        })
      : undefined;
  const artifact: RnMtExpoTargetContextArtifact = {
    schemaVersion: 1,
    target: target.platform
      ? {
          tenant: target.tenant,
          environment: target.environment,
          platform: target.platform,
        }
      : {
          tenant: target.tenant,
          environment: target.environment,
        },
    identity: runtime.identity,
    runtimeConfigPath: "./rn-mt.generated.runtime.json",
    ...(iconPath ? { iconPath } : {}),
    ...(expoConfig?.slug || expoConfig?.scheme
      ? {
          expo: {
            ...(expoConfig.slug ? { slug: expoConfig.slug } : {}),
            ...(expoConfig.scheme ? { scheme: expoConfig.scheme } : {}),
          },
        }
      : {}),
  };

  return {
    path: join(workspace.rootDir, "rn-mt.generated.expo.js"),
    kind: "expo-target-context",
    contents: [
      "// Generated by rn-mt. Expo target context bridge. Do not edit directly.",
      `export default ${JSON.stringify(artifact, null, 2)};`,
      "",
    ].join("\n"),
  };
}

/**
 * Returns true when the repo contains a bare Android project shape.
 */
export function hasBareAndroidProject(workspace: RnMtWorkspace) {
  return [
    join(workspace.rootDir, "android", "app", "build.gradle"),
    join(workspace.rootDir, "android", "app", "build.gradle.kts"),
  ].some((path) => workspace.exists(path));
}

/**
 * Converts a tenant or environment id into a safe Gradle flavor identifier.
 */
export function toGradleFlavorIdentifier(value: string) {
  const segments = value
    .split(/[^a-zA-Z0-9]+/u)
    .map((segment) => segment.replace(/[^a-zA-Z0-9]/gu, ""))
    .filter((segment) => segment.length > 0);

  const [firstSegment = "rnMt", ...remainingSegments] = segments;
  const first = firstSegment.charAt(0).toLowerCase() + firstSegment.slice(1);
  const rest = remainingSegments.map(
    (segment) => segment.charAt(0).toUpperCase() + segment.slice(1),
  );
  const combined = `${first}${rest.join("")}`;

  return /^[a-zA-Z]/u.test(combined)
    ? combined
    : `rnMt${combined.charAt(0).toUpperCase()}${combined.slice(1)}`;
}

/**
 * Escapes a string for safe inclusion in generated Gradle files.
 */
export function toGradleStringLiteral(value: string) {
  return `"${value.replace(/\\/gu, "\\\\").replace(/"/gu, '\\"')}"`;
}

/**
 * Creates android flavor config file.
 */
export function createAndroidFlavorConfigFile(
  workspace: RnMtWorkspace,
  manifest: RnMtManifest,
  runtime: RnMtResolvedRuntimeArtifact,
  target: RnMtResolvedTarget,
): RnMtSyncGeneratedFile {
  const tenantEntries = Object.entries(manifest.tenants).sort(
    ([left], [right]) => left.localeCompare(right),
  );
  const environmentEntries = Object.entries(manifest.environments).sort(
    ([left], [right]) => left.localeCompare(right),
  );
  const selectedVariant = `${toGradleFlavorIdentifier(target.tenant)}${toGradleFlavorIdentifier(
    target.environment,
  )
    .charAt(0)
    .toUpperCase()}${toGradleFlavorIdentifier(target.environment).slice(1)}`;
  const selectedApplicationId = getResolvedAndroidApplicationId(
    runtime.config,
    runtime.identity.nativeId,
  );
  const lines = [
    "// Generated by rn-mt. Android flavor matrix. Do not edit directly.",
    `// Selected target: ${target.tenant}/${target.environment}/android`,
    `// Selected variant: ${selectedVariant}`,
    `// Selected applicationId: ${selectedApplicationId}`,
    "",
    "android {",
    '  flavorDimensions "tenant", "environment"',
    "",
    "  productFlavors {",
  ];

  for (const [tenantId, tenant] of tenantEntries) {
    lines.push(
      `    ${toGradleFlavorIdentifier(tenantId)} {`,
      '      dimension "tenant"',
      `      resValue "string", "RN_MT_TENANT_ID", ${toGradleStringLiteral(tenantId)}`,
      `      resValue "string", "RN_MT_TENANT_DISPLAY_NAME", ${toGradleStringLiteral(
        tenant.displayName,
      )}`,
      "    }",
      "",
    );
  }

  for (const [environmentId, environment] of environmentEntries) {
    const isProduction =
      environmentId === "prod" || environmentId === "production";

    lines.push(
      `    ${toGradleFlavorIdentifier(environmentId)} {`,
      '      dimension "environment"',
      `      resValue "string", "RN_MT_ENVIRONMENT_ID", ${toGradleStringLiteral(
        environmentId,
      )}`,
      `      resValue "string", "RN_MT_ENVIRONMENT_DISPLAY_NAME", ${toGradleStringLiteral(
        environment.displayName,
      )}`,
    );

    if (!isProduction) {
      lines.push(
        `      applicationIdSuffix ${toGradleStringLiteral(`.${environmentId}`)}`,
      );
    }

    lines.push("    }", "");
  }

  lines.push("  }", "}", "");

  return {
    path: join(
      workspace.rootDir,
      "android",
      "app",
      "rn-mt.generated.flavors.gradle",
    ),
    kind: "android-flavor-config",
    contents: lines.join("\n"),
  };
}

/**
 * Creates android native identity file.
 */
export function createAndroidNativeIdentityFile(
  workspace: RnMtWorkspace,
  runtime: RnMtResolvedRuntimeArtifact,
  target: RnMtResolvedTarget,
): RnMtSyncGeneratedFile {
  const applicationId = getResolvedAndroidApplicationId(
    runtime.config,
    runtime.identity.nativeId,
  );

  return {
    path: join(
      workspace.rootDir,
      "android",
      "app",
      "rn-mt.generated.identity.gradle",
    ),
    kind: "android-native-identity",
    contents: [
      "// Generated by rn-mt. Selected Android identity config. Do not edit directly.",
      `// Selected target: ${target.tenant}/${target.environment}/android`,
      "",
      "android {",
      "  defaultConfig {",
      `    applicationId ${toGradleStringLiteral(applicationId)}`,
      `    resValue "string", "app_name", ${toGradleStringLiteral(runtime.identity.displayName)}`,
      "  }",
      "}",
      "",
    ].join("\n"),
  };
}

/**
 * Returns the bare iOS Xcode project name when one exists.
 */
export function getBareIosProjectName(workspace: RnMtWorkspace) {
  const iosDir = join(workspace.rootDir, "ios");

  if (!workspace.isDirectory(iosDir)) {
    return null;
  }

  const projectDirName = readdirSync(iosDir, { withFileTypes: true }).find(
    (entry) => entry.isDirectory() && entry.name.endsWith(".xcodeproj"),
  )?.name;

  return projectDirName ? projectDirName.replace(/\.xcodeproj$/u, "") : null;
}

/**
 * Converts a slug-like value into a PascalCase identifier for generated iOS
 * artifacts.
 */
export function toPascalIdentifier(value: string) {
  const segments = value
    .split(/[^a-zA-Z0-9]+/u)
    .map((segment) => segment.replace(/[^a-zA-Z0-9]/gu, ""))
    .filter((segment) => segment.length > 0);

  if (segments.length === 0) {
    return "RnMt";
  }

  return segments
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

/**
 * Escapes a string for safe inclusion in generated xcconfig files.
 */
export function toXcconfigStringLiteral(value: string) {
  return `"${value.replace(/\\/gu, "\\\\").replace(/"/gu, '\\"')}"`;
}

/**
 * Creates ios native config files.
 */
export function createIosNativeConfigFiles(
  workspace: RnMtWorkspace,
  runtime: RnMtResolvedRuntimeArtifact,
  target: RnMtResolvedTarget,
  xcodeProjectName: string,
) {
  const bundleIdentifier = getResolvedIosBundleIdentifier(
    runtime.config,
    runtime.identity.nativeId,
  );
  const targetSlug = `${target.tenant}-${target.environment}`;
  const targetXcconfigFileName = `rn-mt.generated.${targetSlug}.xcconfig`;
  const currentXcconfigFileName = "rn-mt.generated.current.xcconfig";
  const schemeName = `${toPascalIdentifier(target.tenant)}-${toPascalIdentifier(
    target.environment,
  )}`;
  const schemePath = join(
    workspace.rootDir,
    "ios",
    `${xcodeProjectName}.xcodeproj`,
    "xcshareddata",
    "xcschemes",
    `${schemeName}.xcscheme`,
  );
  const targetXcconfigPath = join(
    workspace.rootDir,
    "ios",
    targetXcconfigFileName,
  );
  const currentXcconfigPath = join(
    workspace.rootDir,
    "ios",
    currentXcconfigFileName,
  );
  const schemeContents = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<Scheme LastUpgradeVersion="9999" version="1.7">',
    "  <!-- Generated by rn-mt. Shared tenant-environment scheme. Do not edit directly. -->",
    `  <!-- Selected target: ${target.tenant}/${target.environment}/ios -->`,
    `  <!-- xcconfig include: ${currentXcconfigFileName} -->`,
    '  <LaunchAction buildConfiguration="Debug">',
    "    <EnvironmentVariables>",
    `      <EnvironmentVariable key=\"RN_MT_TENANT\" value=\"${target.tenant}\" isEnabled=\"YES\" />`,
    `      <EnvironmentVariable key=\"RN_MT_ENVIRONMENT\" value=\"${target.environment}\" isEnabled=\"YES\" />`,
    "    </EnvironmentVariables>",
    "  </LaunchAction>",
    "</Scheme>",
    "",
  ].join("\n");
  const targetXcconfigContents = [
    "// Generated by rn-mt. Selected iOS tenant-environment config. Do not edit directly.",
    `// Selected target: ${target.tenant}/${target.environment}/ios`,
    `PRODUCT_BUNDLE_IDENTIFIER = ${bundleIdentifier}`,
    `INFOPLIST_KEY_CFBundleDisplayName = ${toXcconfigStringLiteral(runtime.identity.displayName)}`,
    `RN_MT_TENANT_ID = ${target.tenant}`,
    `RN_MT_ENVIRONMENT_ID = ${target.environment}`,
    `RN_MT_DISPLAY_NAME = ${toXcconfigStringLiteral(runtime.identity.displayName)}`,
    "",
  ].join("\n");
  const currentXcconfigContents = [
    "// Generated by rn-mt. Selected iOS xcconfig include. Do not edit directly.",
    `#include \"${targetXcconfigFileName}\"`,
    "",
  ].join("\n");

  return [
    {
      path: schemePath,
      kind: "ios-scheme" as const,
      contents: schemeContents,
    },
    {
      path: targetXcconfigPath,
      kind: "ios-xcconfig" as const,
      contents: targetXcconfigContents,
    },
    {
      path: currentXcconfigPath,
      kind: "ios-xcconfig" as const,
      contents: currentXcconfigContents,
    },
  ];
}
