/**
 * Implements the convert core module.
 */
import { readdirSync, type Dirent } from "node:fs";
import { dirname, join, relative } from "node:path";

import { RnMtAnalyzeModule } from "../analyze";
import type { RnMtHostLanguage } from "../analyze/types";
import type { RnMtManifest } from "../manifest/types";
import { createOwnershipMetadataFile } from "../sync";
import type { RnMtSyncGeneratedFile } from "../sync/types";
import { RnMtWorkspace } from "../workspace";

import {
  createCurrentFacadeFile,
  createCurrentFacadeFiles,
  createRootWrapperContents,
  createSourceWrapperContents,
  createBridgeFacadeModuleContents,
  rootWrapperBanner,
} from "./facade-writer";
import {
  createConvertedPackageJsonContents,
  createInstallCommand,
  createStandalonePackageJsonContents,
  getLocalRnMtPackagePlan,
} from "./package-json";
import {
  getAliasRules,
  isFacadeSourceFile,
  isTestSourcePath,
  normalizeImportPath,
  rewriteMovedSourceContents,
  stripSupportedSourceExtension,
} from "./import-rewriter";

import type {
  RnMtAliasRule,
  RnMtCodemodResult,
  RnMtConvertModuleDependencies,
  RnMtConvertMovedFile,
  RnMtConvertResult,
  RnMtConvertRunOptions,
  RnMtReconstructionMetadataFile,
  RnMtReconstructionOriginalPathBehavior,
} from "./types";

const convertibleRootEntryFiles = [
  "App.tsx",
  "App.ts",
  "App.jsx",
  "App.js",
  "index.tsx",
  "index.ts",
  "index.jsx",
  "index.js",
] as const;

const convertCategoryDirNames = [
  "config",
  "theme",
  "assets",
  "__tests__",
  "tests",
] as const;

const convertSourceDirNames = [
  "app",
  "components",
  "hooks",
  "navigators",
  "screens",
  "utils",
  "vectors",
  "services",
  "store",
  "types",
  "context",
  "providers",
  "constants",
  "helpers",
  "hoc",
  "atoms",
  "molecules",
  "organisms",
  "templates",
  "api",
  "data",
  "content",
  "features",
  "convex",
  "theme",
  "config",
  "assets",
] as const;

const convertStandaloneFileNamePattern =
  /^(config|theme|strings?|typography|constants|apiConfig)(\.[^.]+)+$/u;

const expoComputedConfigBridgeBanner =
  "// Generated by rn-mt. Expo computed config bridge. Do not edit directly.";

/**
 * Returns true when a file should be scanned as text during audit and handoff
 * flows.
 */
export function isAuditableTextFile(path: string) {
  return /\.(ts|tsx|js|jsx|json|md|txt)$/u.test(path);
}

/**
 * Lists every file currently living under the converted shared source tree.
 */
export function listSharedFiles(workspace: RnMtWorkspace) {
  const sharedRootDir = workspace.getSharedRootDir();

  if (!workspace.isDirectory(sharedRootDir)) {
    return [];
  }

  return workspace
    .listFiles(sharedRootDir)
    .sort((left, right) => left.localeCompare(right));
}

/**
 * Removes the generated rn-mt guide link section from a README during cleanup
 * or handoff.
 */
export function removeRepoLocalGuideLinkFromReadme(readmeContents: string) {
  const normalizedContents = readmeContents.trimEnd();
  const startMarker = "<!-- rn-mt:guide-link:start -->";
  const endMarker = "<!-- rn-mt:guide-link:end -->";
  const existingStartIndex = normalizedContents.indexOf(startMarker);
  const existingEndIndex = normalizedContents.indexOf(endMarker);

  if (
    existingStartIndex === -1 ||
    existingEndIndex === -1 ||
    existingEndIndex < existingStartIndex
  ) {
    return `${normalizedContents}\n`;
  }

  const before = normalizedContents.slice(0, existingStartIndex).trimEnd();
  const after = normalizedContents
    .slice(existingEndIndex + endMarker.length)
    .trimStart();
  const nextContents = [before, after]
    .filter((segment) => segment.length > 0)
    .join("\n\n");

  return `${nextContents.trimEnd()}\n`;
}

/**
 * Plans and materializes the repo restructuring performed by rn-mt convert.
 */
export class RnMtConvertModule {
  /**
   * Initializes the convert with its shared dependencies.
   */
  constructor(private readonly dependencies: RnMtConvertModuleDependencies) {}

  /**
   * Builds the analyze module used to detect repo shape during conversion.
   */
  private getAnalyzeModule() {
    return new RnMtAnalyzeModule({ workspace: this.dependencies.workspace });
  }

  /**
   * Detects the host language so generated wrappers and extension files use the
   * right syntax.
   */
  private getHostLanguage() {
    return this.getAnalyzeModule().detectHostLanguage(
      this.dependencies.workspace.rootDir,
    ).language;
  }

  /**
   * Runs the convert flow.
   */
  run(options: RnMtConvertRunOptions): RnMtConvertResult {
    const manifest = options.manifest;
    const workspace = this.dependencies.workspace;
    const packageManager = this.getAnalyzeModule().run({
      scopeToProvidedRoot: true,
    }).repo.packageManager;
    const appKind = this.getAnalyzeModule().detectAppKind(
      workspace.rootDir,
    ).kind;
    const localPackages = getLocalRnMtPackagePlan(appKind);
    const aliasRules = getAliasRules(workspace);
    const entryFiles = this.getConvertibleRootEntryFiles();
    const categoryFilePaths = this.getConvertCategoryFilePaths();
    const expoRouterRouteSourcePaths = categoryFilePaths.filter((sourcePath) =>
      this.isExpoRouterRouteSourcePath(sourcePath),
    );
    const packageJsonPath = join(workspace.rootDir, "package.json");
    const bridgeConfigModulePath = this.resolveBridgeConfigModulePath(
      options.bridgeConfigModulePath,
    );

    if (entryFiles.length === 0 && expoRouterRouteSourcePaths.length === 0) {
      throw new Error(
        "No supported host entry files were found. Expected one of App.[jt]sx?, index.[jt]sx?, or an Expo Router app/ route tree.",
      );
    }

    if (
      entryFiles.some((entry) => entry.contents.startsWith(rootWrapperBanner))
    ) {
      throw new Error(
        "Convert has already been applied to this repo. Root entry wrappers are already CLI-owned.",
      );
    }

    const plannedMovedFiles = entryFiles.map((entry) => ({
      sourcePath: entry.path,
      destinationPath: join(workspace.getSharedRootDir(), entry.fileName),
      contents: entry.contents,
    }));
    const categoryMovedFiles = categoryFilePaths
      .filter(
        (sourcePath) => !entryFiles.some((entry) => entry.path === sourcePath),
      )
      .map((sourcePath) => ({
        sourcePath,
        destinationPath: join(
          workspace.getSharedRootDir(),
          sourcePath.startsWith(join(workspace.rootDir, "src"))
            ? join(
                "src",
                sourcePath.slice(join(workspace.rootDir, "src").length + 1),
              )
            : sourcePath.slice(workspace.rootDir.length + 1),
        ),
        contents: this.readMovedFileContents(sourcePath),
        removeSourcePath: this.isExpoRouterRouteSourcePath(sourcePath)
          ? false
          : !this.shouldPreserveOriginalSourcePath(
              sourcePath,
              bridgeConfigModulePath,
            ),
      }));
    const structuralMovedFiles = [...plannedMovedFiles, ...categoryMovedFiles];
    const rootEntrySourcePaths = new Set([
      ...entryFiles.map((entry) => entry.path),
      ...expoRouterRouteSourcePaths,
    ]);
    const currentPathBySourcePath = new Map(
      structuralMovedFiles
        .filter(
          (file) =>
            !isTestSourcePath(relative(workspace.rootDir, file.sourcePath)),
        )
        .map((file) => [
          file.sourcePath,
          join(
            workspace.getCurrentRootDir(),
            file.destinationPath.slice(workspace.getSharedRootDir().length + 1),
          ),
        ]),
    );
    const movedFiles = structuralMovedFiles.map((file) => ({
      ...file,
      contents: isFacadeSourceFile(file.sourcePath)
        ? (() => {
            if (Buffer.isBuffer(file.contents)) {
              throw new Error(
                `Expected source file contents to be text during convert rewrite: ${file.sourcePath}`,
              );
            }

            return rewriteMovedSourceContents(
              workspace,
              file.sourcePath,
              file.destinationPath,
              file.contents,
              currentPathBySourcePath,
              aliasRules,
            );
          })()
        : file.contents,
    }));

    if (workspace.isFile(packageJsonPath)) {
      movedFiles.push({
        sourcePath: packageJsonPath,
        destinationPath: packageJsonPath,
        contents: createConvertedPackageJsonContents(
          workspace.readText(packageJsonPath),
          appKind,
        ),
      });
    }

    const convertedTsconfigContents =
      this.createConvertedTsconfigContents(structuralMovedFiles);

    if (convertedTsconfigContents) {
      const tsconfigPath = join(workspace.rootDir, "tsconfig.json");

      movedFiles.push({
        sourcePath: tsconfigPath,
        destinationPath: tsconfigPath,
        contents: convertedTsconfigContents,
      });
    }

    const rootReadmePath = join(workspace.rootDir, "README.md");

    if (workspace.isFile(rootReadmePath)) {
      movedFiles.push({
        sourcePath: rootReadmePath,
        destinationPath: rootReadmePath,
        contents: this.addRepoLocalGuideLinkToReadme(
          workspace.readText(rootReadmePath),
        ),
      });
    }

    const generatedFiles: RnMtSyncGeneratedFile[] = entryFiles.map((entry) => ({
      path: entry.path,
      kind: "root-wrapper",
      contents: createRootWrapperContents(entry.fileName),
    }));
    generatedFiles.push(
      ...movedFiles.flatMap((file) => {
        if (
          !this.isExpoRouterRouteSourcePath(file.sourcePath) ||
          !isFacadeSourceFile(file.sourcePath)
        ) {
          return [];
        }

        if (Buffer.isBuffer(file.contents)) {
          throw new Error(
            `Expected Expo Router route contents to stay text during convert: ${file.sourcePath}`,
          );
        }

        const currentPath = currentPathBySourcePath.get(file.sourcePath);

        if (!currentPath) {
          throw new Error(
            `Current facade path was not prepared for Expo Router route: ${file.sourcePath}`,
          );
        }

        return [
          {
            path: file.sourcePath,
            kind: "root-wrapper" as const,
            contents: createSourceWrapperContents(
              normalizeImportPath(
                stripSupportedSourceExtension(
                  relative(dirname(file.sourcePath), currentPath),
                ),
              ),
              file.contents,
              relative(workspace.rootDir, file.sourcePath).replace(/\\/gu, "/"),
            ),
          },
        ];
      }),
    );
    generatedFiles.push(
      ...createCurrentFacadeFiles(
        workspace,
        manifest.defaults.tenant,
        structuralMovedFiles.map((file) => ({
          path: file.destinationPath,
          contents: file.contents,
        })),
        this.getHostLanguage(),
      ),
    );

    if (bridgeConfigModulePath) {
      const bridgeMovedFile = movedFiles.find(
        (file) => file.sourcePath === bridgeConfigModulePath,
      );

      if (!bridgeMovedFile) {
        throw new Error(
          `Bridge config module could not be prepared for conversion: ${bridgeConfigModulePath}`,
        );
      }

      generatedFiles.push(
        (() => {
          if (Buffer.isBuffer(bridgeMovedFile.contents)) {
            throw new Error(
              `Expected bridge config module contents to be text: ${bridgeMovedFile.sourcePath}`,
            );
          }

          return this.createHostConfigBridgeFile(
            bridgeMovedFile.sourcePath,
            bridgeMovedFile.destinationPath,
            bridgeMovedFile.contents,
          );
        })(),
      );
    }

    const expoComputedConfigBridgeFile =
      appKind === "expo-managed" || appKind === "expo-prebuild"
        ? this.createExpoComputedConfigBridgeFile(this.getHostLanguage())
        : null;

    if (expoComputedConfigBridgeFile) {
      generatedFiles.push(expoComputedConfigBridgeFile);
    }

    generatedFiles.push({
      path: join(workspace.rootDir, "rn-mt.generated.README.md"),
      kind: "repo-readme",
      contents: this.createRepoLocalGuideContents(),
    });
    generatedFiles.push(
      this.createReconstructionMetadataFile(
        manifest.defaults.tenant,
        structuralMovedFiles,
        currentPathBySourcePath,
        {
          rootEntrySourcePaths,
          bridgeConfigModulePath,
        },
      ),
    );
    const ownershipMetadata = createOwnershipMetadataFile(
      workspace,
      generatedFiles,
      {
        fileName: "rn-mt.generated.convert.ownership.json",
      },
    );
    const hostLanguage = this.getHostLanguage();
    const userOwnedFiles = [
      {
        path: join(
          workspace.getExtensionsRootDir(),
          hostLanguage === "typescript" ? "index.ts" : "index.js",
        ),
        contents: this.createUserOwnedExtensionContents(hostLanguage),
      },
    ];

    return {
      rootDir: workspace.rootDir,
      movedFiles,
      generatedFiles: [...generatedFiles, ownershipMetadata],
      userOwnedFiles,
      packageManager,
      localPackages,
      installCommand: createInstallCommand(packageManager),
    };
  }

  /**
   * Plans the codemod that rewrites shared-source imports to the generated
   * current surface after conversion.
   */
  planCurrentImportsCodemod(
    options: {
      manifest?: RnMtManifest;
    } = {},
  ): RnMtCodemodResult {
    const workspace = this.dependencies.workspace;
    const aliasRules = getAliasRules(workspace);
    const sharedFiles = listSharedFiles(workspace);
    const sharedRootDir = workspace.getSharedRootDir();
    const currentPathBySourcePath = new Map(
      sharedFiles
        .filter(
          (path) =>
            !isTestSourcePath(relative(workspace.getSharedRootDir(), path)),
        )
        .map((path) => [
          path,
          join(
            workspace.rootDir,
            "src",
            "rn-mt",
            "current",
            path.slice(sharedRootDir.length + 1),
          ),
        ]),
    );

    const changes = sharedFiles
      .filter((path) => isFacadeSourceFile(path))
      .map((path) => {
        const before = workspace.readText(path);
        const after = rewriteMovedSourceContents(
          workspace,
          path,
          path,
          before,
          currentPathBySourcePath,
          aliasRules,
        );

        return {
          path,
          before,
          after,
        };
      })
      .filter((change) => change.before !== change.after);

    return {
      rootDir: workspace.rootDir,
      codemod: "current-imports",
      changes,
    };
  }

  /**
   * Checks whether test module file name for the convert flow.
   */
  private isTestModuleFileName(fileName: string) {
    return /\.(test|spec)\.[^.]+$/u.test(fileName);
  }

  /**
   * Returns convert category file paths for the convert flow.
   */
  private getConvertCategoryFilePaths() {
    const workspace = this.dependencies.workspace;
    const categoryFilePaths = new Set<string>();
    const candidateBases = [workspace.rootDir, join(workspace.rootDir, "src")];

    for (const basePath of candidateBases) {
      if (!workspace.isDirectory(basePath)) {
        continue;
      }

      for (const entry of readdirSync(basePath, {
        withFileTypes: true,
      }) as Dirent[]) {
        if (basePath.endsWith("/src") && entry.name === "rn-mt") {
          continue;
        }

        const entryPath = join(basePath, entry.name);

        if (entry.isDirectory() && this.shouldConvertDirectory(basePath, entry)) {
          for (const filePath of workspace.listFiles(entryPath)) {
            if (this.isIgnoredConvertibleFilePath(filePath)) {
              continue;
            }

            categoryFilePaths.add(filePath);
          }
        }

        if (entry.isFile() && this.shouldConvertFile(basePath, entry.name)) {
          categoryFilePaths.add(entryPath);
        }
      }
    }

    return [...categoryFilePaths].sort((left, right) =>
      left.localeCompare(right),
    );
  }

  /**
   * Returns convertible root entry files for the convert flow.
   */
  private getConvertibleRootEntryFiles() {
    const workspace = this.dependencies.workspace;

    return convertibleRootEntryFiles
      .map((fileName) => {
        const path = join(workspace.rootDir, fileName);

        if (!workspace.exists(path)) {
          return null;
        }

        return {
          fileName,
          path,
          contents: workspace.readText(path),
        };
      })
      .filter(
        (
          entry,
        ): entry is {
          fileName: (typeof convertibleRootEntryFiles)[number];
          path: string;
          contents: string;
        } => entry !== null,
      );
  }

  /**
   * Returns true when a source path belongs to the host-facing Expo Router
   * route tree that must stay rooted at app/.
   */
  private isExpoRouterRouteSourcePath(sourcePath: string) {
    if (!this.isExpoRouterEntryApp()) {
      return false;
    }

    const relativeSourcePath = relative(
      this.dependencies.workspace.rootDir,
      sourcePath,
    ).replace(/\\/gu, "/");

    return (
      relativeSourcePath.startsWith("app/") &&
      isFacadeSourceFile(sourcePath) &&
      !isTestSourcePath(relativeSourcePath)
    );
  }

  /**
   * Detects the Expo Router entry model used by modern Expo router repos.
   */
  private isExpoRouterEntryApp() {
    const workspace = this.dependencies.workspace;
    const packageJsonPath = join(workspace.rootDir, "package.json");

    if (!workspace.isFile(packageJsonPath)) {
      return false;
    }

    const packageJson = workspace.readJson<{
      main?: string;
    }>(packageJsonPath);

    return (
      packageJson.main === "expo-router/entry" &&
      workspace.isDirectory(join(workspace.rootDir, "app"))
    );
  }

  /**
   * Checks whether supported bridge config path for the convert flow.
   */
  private isSupportedBridgeConfigPath(sourcePath: string) {
    const relativeSourcePath = relative(
      this.dependencies.workspace.rootDir,
      sourcePath,
    ).replace(/\\/gu, "/");
    const pathSegments = relativeSourcePath.split("/");
    const fileName = pathSegments[pathSegments.length - 1] ?? "";

    return (
      pathSegments.includes("config") ||
      /^config\.(ts|tsx|js|jsx|json)$/u.test(fileName)
    );
  }

  /**
   * Resolves bridge config module path for the convert flow.
   */
  private resolveBridgeConfigModulePath(
    selectedPath: string | null | undefined,
  ) {
    const workspace = this.dependencies.workspace;

    if (!selectedPath) {
      return null;
    }

    const candidatePath = selectedPath.startsWith(workspace.rootDir)
      ? selectedPath
      : join(workspace.rootDir, selectedPath);
    const relativeSelectedPath = relative(workspace.rootDir, candidatePath);

    if (
      relativeSelectedPath.startsWith("..") ||
      !workspace.isFile(candidatePath)
    ) {
      throw new Error(`Bridge config module not found: ${candidatePath}`);
    }

    if (
      !isFacadeSourceFile(candidatePath) ||
      !this.isSupportedBridgeConfigPath(candidatePath)
    ) {
      throw new Error(
        `Bridge mode only supports explicit host config modules. Received: ${candidatePath}`,
      );
    }

    return candidatePath;
  }

  /**
   * Creates host config bridge file for the convert flow.
   */
  private createHostConfigBridgeFile(
    sourcePath: string,
    movedDestinationPath: string,
    sourceContents: string,
  ): RnMtSyncGeneratedFile {
    const workspace = this.dependencies.workspace;
    const sharedRootDir = workspace.getSharedRootDir();
    const relativeSharedPath = movedDestinationPath.slice(
      sharedRootDir.length + 1,
    );
    const currentFacadePath = join(
      workspace.getCurrentRootDir(),
      relativeSharedPath,
    );
    const importPath = normalizeImportPath(
      stripSupportedSourceExtension(
        relative(dirname(sourcePath), currentFacadePath),
      ),
    );

    return {
      path: sourcePath,
      kind: "host-config-bridge",
      contents: createBridgeFacadeModuleContents(importPath, sourceContents),
    };
  }

  /**
   * Returns true when the original source path should remain in place after the
   * converted copy is written into the shared tree.
   */
  private shouldPreserveOriginalSourcePath(
    sourcePath: string,
    bridgeConfigModulePath: string | null,
  ) {
    return (
      sourcePath === bridgeConfigModulePath ||
      this.isPreservedBinaryAssetSourcePath(sourcePath)
    );
  }

  /**
   * Returns true when a binary asset should remain at its original app-facing
   * path even after a shared copy is generated for rn-mt-managed imports.
   */
  private isPreservedBinaryAssetSourcePath(sourcePath: string) {
    const relativeSourcePath = relative(
      this.dependencies.workspace.rootDir,
      sourcePath,
    ).replace(/\\/gu, "/");

    return (
      relativeSourcePath.split("/").includes("assets") &&
      /\.(png|jpg|jpeg|svg|ttf|otf)$/u.test(sourcePath)
    );
  }

  /**
   * Returns true when the repo already defines its own Expo computed config
   * layer and rn-mt should not generate one.
   */
  private hasExistingExpoComputedConfig() {
    const workspace = this.dependencies.workspace;

    return [
      join(workspace.rootDir, "app.config.ts"),
      join(workspace.rootDir, "app.config.js"),
    ].some((path) => workspace.isFile(path));
  }

  /**
   * Creates the default Expo computed config bridge for app.json-only repos so
   * target context can flow through Expo's computed config layer.
   */
  private createExpoComputedConfigBridgeFile(
    hostLanguage: RnMtHostLanguage,
  ): RnMtSyncGeneratedFile | null {
    const workspace = this.dependencies.workspace;
    const appJsonPath = join(workspace.rootDir, "app.json");

    if (!workspace.isFile(appJsonPath) || this.hasExistingExpoComputedConfig()) {
      return null;
    }

    const path = join(
      workspace.rootDir,
      hostLanguage === "typescript" ? "app.config.ts" : "app.config.js",
    );
    const contents =
      hostLanguage === "typescript"
        ? [
            expoComputedConfigBridgeBanner,
            'import appJson from "./app.json";',
            'import { applyExpoTargetContext } from "@rn-mt/expo-plugin";',
            'import type { RnMtExpoTargetContext } from "@rn-mt/expo-plugin";',
            'import targetContext from "./rn-mt.generated.expo.js";',
            "",
            "export default applyExpoTargetContext(",
            "  appJson.expo,",
            "  targetContext as RnMtExpoTargetContext,",
            ");",
            "",
          ].join("\n")
        : [
            expoComputedConfigBridgeBanner,
            'const appJson = require("./app.json");',
            'const { applyExpoTargetContext } = require("@rn-mt/expo-plugin");',
            'const targetContext = require("./rn-mt.generated.expo.js").default;',
            "",
            "module.exports = applyExpoTargetContext(appJson.expo, targetContext);",
            "",
          ].join("\n");

    return {
      path,
      kind: "expo-config-bridge",
      contents,
    };
  }

  /**
   * Creates user owned extension contents for the convert flow.
   */
  private createUserOwnedExtensionContents(hostLanguage: RnMtHostLanguage) {
    return [
      "// User-owned rn-mt extension module. Safe to edit.",
      "// Add custom helpers here instead of editing CLI-owned generated files.",
      hostLanguage === "typescript"
        ? "export const rnMtExtensions = {} as const;"
        : "export const rnMtExtensions = {};",
      "",
    ].join("\n");
  }

  /**
   * Rewrites tsconfig path aliases so aliases that point entirely at converted
   * trees now resolve through the generated current surface.
   */
  private createConvertedTsconfigContents(
    structuralMovedFiles: RnMtConvertMovedFile[],
  ) {
    const workspace = this.dependencies.workspace;
    const tsconfigPath = join(workspace.rootDir, "tsconfig.json");

    if (!workspace.isFile(tsconfigPath)) {
      return null;
    }

    const tsconfig = workspace.readJson<{
      compilerOptions?: {
        baseUrl?: string;
        paths?: Record<string, string[]>;
      };
      [key: string]: unknown;
    }>(tsconfigPath);
    const baseUrl = tsconfig.compilerOptions?.baseUrl ?? ".";
    const paths = tsconfig.compilerOptions?.paths;

    if (!paths) {
      return null;
    }

    const baseUrlRoot = join(workspace.rootDir, baseUrl);
    const movedSourcePaths = new Set(
      structuralMovedFiles.map((file) => file.sourcePath),
    );
    const shouldInjectBaseUrl = !tsconfig.compilerOptions?.baseUrl;
    let changed = shouldInjectBaseUrl;
    const nextPaths = Object.fromEntries(
      Object.entries(paths).map(([key, targets]) => [
        key,
        targets.map((target) => {
          const nextTarget = this.rewriteConvertedTsconfigAliasTarget(
            baseUrlRoot,
            target,
            movedSourcePaths,
          );

          if (nextTarget !== target) {
            changed = true;
          }

          return nextTarget;
        }),
      ]),
    );

    if (!changed) {
      return null;
    }

    return `${JSON.stringify(
      {
        ...tsconfig,
        compilerOptions: {
          ...(tsconfig.compilerOptions ?? {}),
          baseUrl,
          paths: nextPaths,
        },
      },
      null,
      2,
    )}\n`;
  }

  /**
   * Repoints a single tsconfig alias target at the generated current surface
   * when the alias exclusively targets files that convert into shared/current.
   */
  private rewriteConvertedTsconfigAliasTarget(
    baseUrlRoot: string,
    target: string,
    movedSourcePaths: Set<string>,
  ) {
    const wildcardSuffix = target.endsWith("/*") ? "/*" : "";
    const normalizedTarget = wildcardSuffix
      ? target.slice(0, -wildcardSuffix.length)
      : target;
    const resolvedTargetPath = join(baseUrlRoot, normalizedTarget);

    if (
      !this.isFullyConvertedAliasTargetPath(
        resolvedTargetPath,
        movedSourcePaths,
      )
    ) {
      return target;
    }

    const rewrittenTargetBasePath = join(
      this.dependencies.workspace.getCurrentRootDir(),
      relative(this.dependencies.workspace.rootDir, resolvedTargetPath),
    );
    const relativeTarget = relative(baseUrlRoot, rewrittenTargetBasePath)
      .replace(/\\/gu, "/")
      .replace(/^$/u, ".");

    return wildcardSuffix ? `${relativeTarget}${wildcardSuffix}` : relativeTarget;
  }

  /**
   * Returns true when a tsconfig alias target points only at files that are
   * being converted into shared/current.
   */
  private isFullyConvertedAliasTargetPath(
    resolvedTargetPath: string,
    movedSourcePaths: Set<string>,
  ) {
    const workspace = this.dependencies.workspace;

    if (!this.isConvertibleAliasTargetPath(resolvedTargetPath)) {
      return false;
    }

    if (workspace.isFile(resolvedTargetPath)) {
      return movedSourcePaths.has(resolvedTargetPath);
    }

    if (!workspace.isDirectory(resolvedTargetPath)) {
      return false;
    }

    const filePaths = workspace.listFiles(resolvedTargetPath);

    return filePaths.length > 0 && filePaths.every((path) => movedSourcePaths.has(path));
  }

  /**
   * Returns true when a tsconfig alias target is anchored on one of the
   * convert-managed category roots instead of a broader parent directory.
   */
  private isConvertibleAliasTargetPath(resolvedTargetPath: string) {
    return (
      this.dependencies.workspace.isFile(resolvedTargetPath) ||
      this.dependencies.workspace.isDirectory(resolvedTargetPath)
    );
  }

  /**
   * Returns true when a directory under the repo root or src root should move
   * into the shared/current managed tree during conversion.
   */
  private shouldConvertDirectory(basePath: string, entry: Dirent) {
    if (entry.name.startsWith(".") || this.isExcludedDirectoryName(entry.name)) {
      return false;
    }

    if (basePath.endsWith("/src")) {
      return this.directoryContainsConvertibleFiles(join(basePath, entry.name));
    }

    return convertSourceDirNames.includes(
      entry.name as (typeof convertSourceDirNames)[number],
    );
  }

  /**
   * Returns true when a standalone file under the repo root or src root should
   * move into the managed shared/current tree during conversion.
   */
  private shouldConvertFile(basePath: string, fileName: string) {
    if (fileName.startsWith(".")) {
      return false;
    }

    const isConvertCategoryFile = convertCategoryDirNames.some(
      (name) =>
        fileName === `${name}.ts` ||
        fileName === `${name}.tsx` ||
        fileName === `${name}.js` ||
        fileName === `${name}.jsx` ||
        fileName === `${name}.json`,
    );

    if (isConvertCategoryFile || this.isTestModuleFileName(fileName)) {
      return true;
    }

    if (basePath.endsWith("/src")) {
      return /\.(ts|tsx|js|jsx|json)$/u.test(fileName);
    }

    return convertStandaloneFileNamePattern.test(fileName);
  }

  /**
   * Returns true when a directory name should never be treated as convertible
   * shared source during repo restructuring.
   */
  private isExcludedDirectoryName(directoryName: string) {
    return [
      "node_modules",
      "ios",
      "android",
      "web",
      "coverage",
      "dist",
      "build",
      ".expo",
      ".git",
      ".vscode",
      "rn-mt",
    ].includes(directoryName);
  }

  /**
   * Returns true when a discovered file path should stay out of convert
   * planning because it belongs to hidden OS/editor metadata.
   */
  private isIgnoredConvertibleFilePath(filePath: string) {
    return filePath
      .split(/[/\\]/u)
      .some((segment) => segment.startsWith(".") && segment.length > 1);
  }

  /**
   * Returns true when a directory actually contains user-owned app source or
   * static content that should participate in conversion.
   */
  private directoryContainsConvertibleFiles(directoryPath: string) {
    const filePaths = this.dependencies.workspace.listFiles(directoryPath);

    return filePaths.some((filePath) =>
      /\.(ts|tsx|js|jsx|json|png|jpg|jpeg|svg|ttf|otf)$/u.test(filePath),
    );
  }

  /**
   * Reads a convertible source file using text IO for textual sources and raw
   * byte IO for binary assets so convert can preserve bytes exactly.
   */
  private readMovedFileContents(sourcePath: string) {
    return this.isBinaryConvertibleFile(sourcePath)
      ? this.dependencies.workspace.readBuffer(sourcePath)
      : this.dependencies.workspace.readText(sourcePath);
  }

  /**
   * Returns true when a convertible source path must be preserved as binary
   * bytes instead of being decoded as UTF-8 text during conversion.
   */
  private isBinaryConvertibleFile(sourcePath: string) {
    return /\.(png|jpg|jpeg|ttf|otf)$/u.test(sourcePath);
  }

  /**
   * Creates repo local guide contents for the convert flow.
   */
  private createRepoLocalGuideContents() {
    return [
      "# rn-mt Ownership and Handoff Guide",
      "",
      "## CLI-owned files",
      "",
      "Do not edit rn-mt generated files directly. Re-run `rn-mt convert`, `rn-mt sync`, or other rn-mt commands instead.",
      "",
      "Common CLI-owned paths in this repo:",
      "",
      "- Root wrapper files such as `App.tsx`, `App.js`, `index.ts`, or `index.js` after conversion",
      "- `src/rn-mt/current/**` current facades",
      "- `rn-mt.generated.convert.ownership.json`",
      "- `rn-mt.generated.reconstruction.json`",
      "- `rn-mt.generated.runtime.json`",
      "- `rn-mt.generated.ownership.json`",
      "- Generated native include files, Expo bridge files, and derived assets written by `rn-mt sync`",
      "",
      "## User-owned files",
      "",
      "Make product changes in the user-owned surfaces:",
      "",
      "- `rn-mt.config.json`",
      "- `src/rn-mt/shared/**`",
      "- `src/rn-mt/tenants/**`",
      "- `src/rn-mt/extensions/**`",
      "",
      "Use `rn-mt override create <path>` when a shared file needs a tenant-specific override.",
      "",
      "## Handoff expectations",
      "",
      "A future `rn-mt handoff --tenant <id>` flow is expected to:",
      "",
      "- Create a new sibling output repo instead of mutating this workspace in place",
      "- Remove rn-mt-specific machinery from the delivered tenant repo",
      "- Strip git history by default and sanitize env files before delivery",
      "- Depend on a healthy repo with clean sync output and a clean audit result",
      "",
    ].join("\n");
  }

  /**
   * Creates repo local guide link section for the convert flow.
   */
  private createRepoLocalGuideLinkSection() {
    return [
      "<!-- rn-mt:guide-link:start -->",
      "## rn-mt",
      "",
      "See [rn-mt ownership and handoff guide](./rn-mt.generated.README.md) for CLI-owned files, user-owned extension points, and handoff expectations.",
      "<!-- rn-mt:guide-link:end -->",
      "",
    ].join("\n");
  }

  /**
   * Injects or refreshes the README section that points developers at the
   * generated rn-mt ownership guide.
   */
  private addRepoLocalGuideLinkToReadme(readmeContents: string) {
    const linkSection = this.createRepoLocalGuideLinkSection();
    const normalizedContents = readmeContents.trimEnd();
    const startMarker = "<!-- rn-mt:guide-link:start -->";
    const endMarker = "<!-- rn-mt:guide-link:end -->";
    const existingStartIndex = normalizedContents.indexOf(startMarker);
    const existingEndIndex = normalizedContents.indexOf(endMarker);

    if (
      existingStartIndex !== -1 &&
      existingEndIndex !== -1 &&
      existingEndIndex > existingStartIndex
    ) {
      return `${normalizedContents.slice(0, existingStartIndex)}${linkSection}${normalizedContents.slice(existingEndIndex + endMarker.length).replace(/^\n*/u, "")}`.replace(
        /\n{3,}/gu,
        "\n\n",
      );
    }

    if (normalizedContents.length === 0) {
      return linkSection;
    }

    return `${normalizedContents}\n\n${linkSection}`;
  }

  /**
   * Creates reconstruction metadata file for the convert flow.
   */
  private createReconstructionMetadataFile(
    defaultTenant: string,
    movedFiles: RnMtConvertMovedFile[],
    currentPathBySourcePath: Map<string, string>,
    options: {
      rootEntrySourcePaths: Set<string>;
      bridgeConfigModulePath?: string | null;
    },
  ): RnMtSyncGeneratedFile {
    const workspace = this.dependencies.workspace;
    const metadata: RnMtReconstructionMetadataFile = {
      schemaVersion: 1,
      tool: "rn-mt",
      defaultTenant,
      sharedRootPath: relative(workspace.rootDir, workspace.getSharedRootDir()),
      currentRootPath: relative(
        workspace.rootDir,
        workspace.getCurrentRootDir(),
      ),
      entries: movedFiles
        .map((file) => {
          const currentPath = currentPathBySourcePath.get(file.sourcePath);
          const originalPathBehavior: RnMtReconstructionOriginalPathBehavior =
            options.rootEntrySourcePaths.has(file.sourcePath)
              ? "replaced-with-root-wrapper"
              : file.sourcePath === options.bridgeConfigModulePath
                ? "replaced-with-host-config-bridge"
                : file.removeSourcePath === false
                  ? "preserved"
                  : "removed";

          const entry = {
            originalPath: relative(workspace.rootDir, file.sourcePath),
            sharedPath: relative(workspace.rootDir, file.destinationPath),
            originalPathBehavior,
          };

          return currentPath
            ? {
                ...entry,
                currentPath: relative(workspace.rootDir, currentPath),
              }
            : entry;
        })
        .sort((left, right) =>
          left.originalPath.localeCompare(right.originalPath),
        ),
    };

    return {
      path: join(workspace.rootDir, "rn-mt.generated.reconstruction.json"),
      kind: "reconstruction-metadata",
      contents: `${JSON.stringify(metadata, null, 2)}\n`,
    };
  }
}
