import { dirname, join, relative } from "node:path";

import type { RnMtHostLanguage } from "../analyze/types";
import { RnMtWorkspace } from "../workspace";

import type { RnMtSyncGeneratedFile } from "../sync/types";

import {
  hasDefaultExportSyntax,
  isFacadeSourceFile,
  isTestSourcePath,
  normalizeImportPath,
  stripSupportedSourceExtension,
} from "./import-rewriter";

export const rootWrapperBanner =
  "// Generated by rn-mt. CLI-owned wrapper. Do not edit directly.";

export function createRootWrapperContents(fileName: string) {
  if (fileName.startsWith("App.")) {
    return [
      rootWrapperBanner,
      'import App from "./src/rn-mt/current/App";',
      "",
      "export default App;",
      "",
    ].join("\n");
  }

  return [rootWrapperBanner, 'import "./src/rn-mt/current/index";', "",].join("\n");
}

export function createCurrentFacadeModuleContents(
  targetImportPath: string,
  sourceContents: string,
  relativeSharedPath: string,
) {
  const header = "// Generated by rn-mt. CLI-owned current facade. Do not edit directly.";

  if (/^index\.(ts|tsx|js|jsx)$/u.test(relativeSharedPath)) {
    return [header, `import "${targetImportPath}";`, "",].join("\n");
  }

  const lines = [header];

  if (hasDefaultExportSyntax(sourceContents)) {
    lines.push(`export { default } from "${targetImportPath}";`);
  }

  lines.push(`export * from "${targetImportPath}";`, "");
  return lines.join("\n");
}

export function createBridgeFacadeModuleContents(
  targetImportPath: string,
  sourceContents: string,
) {
  const lines = [
    "// Generated by rn-mt. CLI-owned host config bridge. Optional bridge mode. Do not edit directly.",
  ];

  if (hasDefaultExportSyntax(sourceContents)) {
    lines.push(`export { default } from "${targetImportPath}";`);
  }

  lines.push(`export * from "${targetImportPath}";`, "");
  return lines.join("\n");
}

export function createRuntimeFacadeContents(hostLanguage: RnMtHostLanguage) {
  const importLine =
    hostLanguage === "typescript"
      ? 'import runtime from "../../../rn-mt.generated.runtime.json";'
      : 'import runtime from "../../../rn-mt.generated.runtime.json";';

  return [
    "// Generated by rn-mt. CLI-owned current runtime facade. Do not edit directly.",
    importLine,
    'import { createRuntimeAccessors } from "@rn-mt/runtime";',
    "",
    "const runtimeAccessors = createRuntimeAccessors(runtime);",
    "",
    "export const getConfig = runtimeAccessors.getConfig;",
    "export const getTenant = runtimeAccessors.getTenant;",
    "export const getEnv = runtimeAccessors.getEnv;",
    "export const getFlags = runtimeAccessors.getFlags;",
    "export const getAssets = runtimeAccessors.getAssets;",
    "export const getRoutes = runtimeAccessors.getRoutes;",
    "export const getFeatures = runtimeAccessors.getFeatures;",
    "export const getMenus = runtimeAccessors.getMenus;",
    "export const getActions = runtimeAccessors.getActions;",
    "",
    "export default runtimeAccessors;",
    "",
  ].join("\n");
}

export function createCurrentFacadeFile(
  workspace: RnMtWorkspace,
  tenantId: string,
  sharedFile: { path: string; contents: string },
  options: {
    preferShared?: boolean;
    overrideFile?: {
      path: string;
      contents: string;
    };
  } = {},
): RnMtSyncGeneratedFile {
  const sharedRootDir = workspace.getSharedRootDir();
  const relativeSharedPath = sharedFile.path.slice(sharedRootDir.length + 1);
  const tenantOverridePath = join(workspace.getTenantRootDir(tenantId), relativeSharedPath);
  const facadePath = join(workspace.getCurrentRootDir(), relativeSharedPath);
  const overrideFile = options.overrideFile;
  const preferShared = options.preferShared ?? false;
  const resolvedSourcePath = overrideFile?.path
    ? overrideFile.path
    : !preferShared && workspace.isFile(tenantOverridePath)
      ? tenantOverridePath
      : sharedFile.path;
  const resolvedSourceContents = overrideFile?.contents
    ?? (resolvedSourcePath === sharedFile.path
      ? sharedFile.contents
      : workspace.readText(resolvedSourcePath));
  const importPath = normalizeImportPath(
    stripSupportedSourceExtension(relative(dirname(facadePath), resolvedSourcePath)),
  );

  return isFacadeSourceFile(sharedFile.path)
    ? {
        path: facadePath,
        kind: "current-facade",
        contents: createCurrentFacadeModuleContents(
          importPath,
          resolvedSourceContents,
          relativeSharedPath,
        ),
      }
    : {
        path: facadePath,
        kind: "current-facade",
        contents: resolvedSourceContents,
      };
}

export function createCurrentFacadeFiles(
  workspace: RnMtWorkspace,
  tenantId: string,
  sharedFiles: Array<{ path: string; contents: string }>,
  hostLanguage: RnMtHostLanguage,
) {
  const facadeFiles: RnMtSyncGeneratedFile[] = [];

  for (const sharedFile of sharedFiles) {
    if (isTestSourcePath(sharedFile.path)) {
      continue;
    }

    facadeFiles.push(createCurrentFacadeFile(workspace, tenantId, sharedFile));
  }

  facadeFiles.push({
    path: join(
      workspace.rootDir,
      "src",
      "rn-mt",
      "current",
      hostLanguage === "typescript" ? "runtime.ts" : "runtime.js",
    ),
    kind: "current-facade",
    contents: createRuntimeFacadeContents(hostLanguage),
  });

  return facadeFiles;
}
