/**
 * Builds generated facade files during repo conversion.
 */
import { dirname, join, relative } from "node:path";

import type { RnMtHostLanguage } from "../analyze/types";
import { RnMtWorkspace } from "../workspace";

import type { RnMtSyncGeneratedFile } from "../sync/types";

import {
  hasDefaultExportSyntax,
  hasExportSyntax,
  isFacadeSourceFile,
  isTestSourcePath,
  normalizeImportPath,
  stripSupportedSourceExtension,
} from "./import-rewriter";

export const rootWrapperBanner =
  "// Generated by rn-mt. CLI-owned wrapper. Do not edit directly.";

/**
 * Builds either a side-effect-only wrapper or an export-forwarding wrapper for
 * host-facing source files such as Expo Router route modules.
 */
function createFacadeModuleContents(
  header: string,
  targetImportPath: string,
  sourceContents: string,
  relativeSourcePath: string,
) {
  if (/^index\.(ts|tsx|js|jsx)$/u.test(relativeSourcePath)) {
    return [header, `import "${targetImportPath}";`, ""].join("\n");
  }

  const lines = [header];

  if (!hasExportSyntax(sourceContents)) {
    lines.push(`import "${targetImportPath}";`, "");
    return lines.join("\n");
  }

  if (hasDefaultExportSyntax(sourceContents)) {
    lines.push(`export { default } from "${targetImportPath}";`);
  }

  lines.push(`export * from "${targetImportPath}";`, "");
  return lines.join("\n");
}

/**
 * Creates root wrapper contents.
 */
export function createRootWrapperContents(fileName: string) {
  if (fileName.startsWith("App.")) {
    return [
      rootWrapperBanner,
      'import App from "./src/rn-mt/current/App";',
      "",
      "export default App;",
      "",
    ].join("\n");
  }

  return [rootWrapperBanner, 'import "./src/rn-mt/current/index";', ""].join(
    "\n",
  );
}

/**
 * Creates wrapper contents for host-facing files that need to stay in place,
 * such as Expo Router route modules under the root app tree.
 */
export function createSourceWrapperContents(
  targetImportPath: string,
  sourceContents: string,
  relativeSourcePath: string,
) {
  return createFacadeModuleContents(
    rootWrapperBanner,
    targetImportPath,
    sourceContents,
    relativeSourcePath,
  );
}

/**
 * Creates current facade module contents.
 */
export function createCurrentFacadeModuleContents(
  targetImportPath: string,
  sourceContents: string,
  relativeSharedPath: string,
) {
  return createFacadeModuleContents(
    "// Generated by rn-mt. CLI-owned current facade. Do not edit directly.",
    targetImportPath,
    sourceContents,
    relativeSharedPath,
  );
}

/**
 * Creates bridge facade module contents.
 */
export function createBridgeFacadeModuleContents(
  targetImportPath: string,
  sourceContents: string,
) {
  const lines = [
    "// Generated by rn-mt. CLI-owned host config bridge. Optional bridge mode. Do not edit directly.",
  ];

  if (hasDefaultExportSyntax(sourceContents)) {
    lines.push(`export { default } from "${targetImportPath}";`);
  }

  lines.push(`export * from "${targetImportPath}";`, "");
  return lines.join("\n");
}

/**
 * Creates runtime facade contents.
 */
export function createRuntimeFacadeContents(hostLanguage: RnMtHostLanguage) {
  const importLine =
    hostLanguage === "typescript"
      ? 'import runtime from "../../../rn-mt.generated.runtime.json";'
      : 'import runtime from "../../../rn-mt.generated.runtime.json";';

  return [
    "// Generated by rn-mt. CLI-owned current runtime facade. Do not edit directly.",
    importLine,
    'import { createRuntimeAccessors } from "@molaidrislabs/runtime";',
    "",
    "const runtimeAccessors = createRuntimeAccessors(runtime);",
    "",
    "export const getConfig = runtimeAccessors.getConfig;",
    "export const getTenant = runtimeAccessors.getTenant;",
    "export const getEnv = runtimeAccessors.getEnv;",
    "export const getFlags = runtimeAccessors.getFlags;",
    "export const getAssets = runtimeAccessors.getAssets;",
    "export const getRoutes = runtimeAccessors.getRoutes;",
    "export const getFeatures = runtimeAccessors.getFeatures;",
    "export const getMenus = runtimeAccessors.getMenus;",
    "export const getActions = runtimeAccessors.getActions;",
    "",
    "export default runtimeAccessors;",
    "",
  ].join("\n");
}

/**
 * Creates current facade file.
 */
export function createCurrentFacadeFile(
  workspace: RnMtWorkspace,
  tenantId: string,
  sharedFile: { path: string; contents: string | Buffer },
  options: {
    preferShared?: boolean;
    overrideFile?: {
      path: string;
      contents: string | Buffer;
    };
  } = {},
): RnMtSyncGeneratedFile {
  const sharedRootDir = workspace.getSharedRootDir();
  const relativeSharedPath = sharedFile.path.slice(sharedRootDir.length + 1);
  const tenantOverridePath = join(
    workspace.getTenantRootDir(tenantId),
    relativeSharedPath,
  );
  const facadePath = join(workspace.getCurrentRootDir(), relativeSharedPath);
  const overrideFile = options.overrideFile;
  const preferShared = options.preferShared ?? false;
  const resolvedSourcePath = overrideFile?.path
    ? overrideFile.path
    : !preferShared && workspace.isFile(tenantOverridePath)
      ? tenantOverridePath
      : sharedFile.path;
  const resolvedSourceContents =
    overrideFile?.contents ??
    (resolvedSourcePath === sharedFile.path
      ? sharedFile.contents
      : isFacadeSourceFile(sharedFile.path)
        ? workspace.readText(resolvedSourcePath)
        : workspace.readBuffer(resolvedSourcePath));
  const importPath = normalizeImportPath(
    stripSupportedSourceExtension(
      relative(dirname(facadePath), resolvedSourcePath),
    ),
  );
  const resolvedSourceText =
    typeof resolvedSourceContents === "string"
      ? resolvedSourceContents
      : resolvedSourceContents.toString("utf8");

  return isFacadeSourceFile(sharedFile.path)
    ? {
        path: facadePath,
        kind: "current-facade",
        contents: createCurrentFacadeModuleContents(
          importPath,
          resolvedSourceText,
          relativeSharedPath,
        ),
      }
    : {
        path: facadePath,
        kind: "current-facade",
        contents: resolvedSourceContents,
      };
}

/**
 * Creates current facade files.
 */
export function createCurrentFacadeFiles(
  workspace: RnMtWorkspace,
  tenantId: string,
  sharedFiles: Array<{ path: string; contents: string | Buffer }>,
  hostLanguage: RnMtHostLanguage,
) {
  const facadeFiles: RnMtSyncGeneratedFile[] = [];

  for (const sharedFile of sharedFiles) {
    const relativeSharedPath = relative(
      workspace.getSharedRootDir(),
      sharedFile.path,
    );

    if (isTestSourcePath(relativeSharedPath)) {
      continue;
    }

    facadeFiles.push(createCurrentFacadeFile(workspace, tenantId, sharedFile));
  }

  facadeFiles.push({
    path: join(
      workspace.rootDir,
      "src",
      "rn-mt",
      "current",
      hostLanguage === "typescript" ? "runtime.ts" : "runtime.js",
    ),
    kind: "current-facade",
    contents: createRuntimeFacadeContents(hostLanguage),
  });

  return facadeFiles;
}
